.Install Python package manager Poetry
----
https://github.com/weipingc/poetry
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

in ~/.zshrc, add the following line:
export PATH="$HOME/.poetry/bin:$PATH"
----

.Try it out
----
➜  pythonLab git:(master) ✗ mkdir tryPoetry
pyenv versions
➜  pythonLab git:(master) ✗ cd tryPoetry
➜  tryPoetry git:(master) ✗ poetry new hellopoetry
➜  tryPoetry git:(master) ✗ poetry add numpy
➜  tryPoetry git:(master) ✗ poetry install
➜  tryPoetry git:(master) ✗ pyenv versions
  system
  3.4.10
* 3.7.4 (set by /Users/Wei/.pyenv/version)
➜  tryPoetry git:(master) ✗ ls -d /Users/Wei/Library/Caches/pypoetry/virtualenvs/hellopoetry-py3.7/lib/python3.7/site-packages/numpy*
/Users/Wei/Library/Caches/pypoetry/virtualenvs/hellopoetry-py3.7/lib/python3.7/site-packages/numpy
/Users/Wei/Library/Caches/pypoetry/virtualenvs/hellopoetry-py3.7/lib/python3.7/site-packages/numpy-1.17.2.dist-info

➜  tryPoetry git:(master) ✗ vi pyproject.toml
Add the following lines:
[tool.poetry.scripts]
hello = "hellopoetry.console:main"

(The following line will cause Poetry to run
  python -c "import hellopoetry.console as con; con.main()"
with all dependency specified in pyproject.toml)
➜  tryPoetry git:(master) ✗ poetry run hello
[Application.__init__]
[Application.run] Hi App by Poetry!
➜  tryPoetry git:(master) ✗
